version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  db:
    image: mongo:latest